### ISSUE TITLE
Crashes on iOS

### ISSUE THREAD

**Issue by alexobviously** [ukasz123/soundpool#47]
Hi, we're using soundpool in our app and everything seemed to be working fine in testing, including on iOS devices. However, now it's published and we're getting some crash reports from apple. The app hasn't been extensively marketed yet fortunately, so these are just from testers, and it seems like it's something to do with the device being allowed to sleep with the app open and crashing. I'm not sure that that's the cause in all of the cases, just what one tester reported. No problems on Android, only iOS.

<img width="1201" alt="soundpool crash 1" src="https://user-images.githubusercontent.com/2500696/94331997-5e2b6d80-fffb-11ea-9210-c9f0abfcd4dc.png">
<img width="1204" alt="soundpool crash 2" src="https://user-images.githubusercontent.com/2500696/94331999-5f5c9a80-fffb-11ea-9628-14b7d86eab16.png">

**Comment by ukasz123** [comment]
Not 100% sure but there was unguarded path when invalid value of `soundId` was passed to `play()`. This has been fixed in version `1.1.2`.
Please, check your implementation if you correctly track soundIds in your app.

**Comment by alexobviously** [comment]
Okay, just checking back in here. I updated to 1.1.2 and I thought that fixed it, but we're still getting the errors. Our soundIDs are tracked correctly and we're not doing anything particularly complicated. Any ideas?

Here's one crash log, I can give you some more if you want but they all look basically like this:
```
Date/Time:           2020-10-26 21:04:34.3849 +0000
Launch Time:         2020-10-26 19:39:09.3550 +0000
OS Version:          iPhone OS 13.6 (17G68)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001012e1b50
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [28623]
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   soundpool                     	0x00000001012e1b50 Swift runtime failure: Index out of range + 0 (<compiler-generated>:0)
1   soundpool                     	0x00000001012e1b50 specialized _ArrayBuffer._nativeTypeChecked.getter + 0 (<compiler-generated>:0)
2   soundpool                     	0x00000001012e1b50 specialized Array._getElement(_:wasNativeTypeChecked:matchingSubscriptCheck:) + 0 (SwiftSoundpoolPlugin.swift:26)
3   soundpool                     	0x00000001012e1b50 specialized Array.subscript.getter + 0 (SwiftSoundpoolPlugin.swift:27)
4   soundpool                     	0x00000001012e1b50 specialized SwiftSoundpoolPlugin.handle(_:result:) + 2544
5   soundpool                     	0x00000001012e16e0 specialized SwiftSoundpoolPlugin.handle(_:result:) + 1408 (SwiftSoundpoolPlugin.swift:27)
6   soundpool                     	0x00000001012da188 specialized SwiftSoundpoolPlugin.handle(_:result:) + 12 (<compiler-generated>:0)
7   soundpool                     	0x00000001012da188 @objc SwiftSoundpoolPlugin.handle(_:result:) + 76
8   Flutter                       	0x0000000101b36234 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 116 (FlutterChannels.mm:245)
9   Flutter                       	0x00000001015fdfa8 flutter::PlatformMessageRouter::HandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>) const + 140 (platform_message_router.mm:27)
10  Flutter                       	0x00000001015fdfa8 flutter::PlatformViewIOS::HandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>) + 504 (platform_view_ios.mm:62)
11  Flutter                       	0x00000001018d5d98 flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33::operator()() const + 88 (shell.cc:1081)
12  Flutter                       	0x00000001018d5d98 decltype(std::__1::forward<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33&>(fp)()) std::__1::__invoke<flutter::Shell::OnEngineHandlePlatformMessage(fml::... + 88 (type_traits:4361)
13  Flutter                       	0x00000001018d5d98 void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33&>(flutter::Shell::OnEngineHandlePlatformMessage(... + 88 (__functional_base:349)
14  Flutter                       	0x00000001018d5d98 std::__1::__function::__alloc_func<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33, std::__1::allocator<flutter::Shell::OnEngineHandlePlatformMessage(fml:... + 88 (functional:1527)
15  Flutter                       	0x00000001018d5d98 std::__1::__function::__func<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33, std::__1::allocator<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPt... + 108 (functional:1651)
16  Flutter                       	0x000000010160744c std::__1::__function::__value_func<void ()>::operator()() const + 12 (functional:1799)
17  Flutter                       	0x000000010160744c std::__1::function<void ()>::operator()() const + 12 (functional:2347)
18  Flutter                       	0x000000010160744c fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 1460 (message_loop_impl.cc:130)
19  Flutter                       	0x00000001016093c0 fml::MessageLoopImpl::RunExpiredTasksNow() + 8 (message_loop_impl.cc:143)
20  Flutter                       	0x00000001016093c0 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32 (message_loop_darwin.mm:75)
21  CoreFoundation                	0x00000001a31f9134 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28 (CFRunLoop.c:1766)
22  CoreFoundation                	0x00000001a31f8e50 __CFRunLoopDoTimer + 880 (CFRunLoop.c:2357)
23  CoreFoundation                	0x00000001a31f852c __CFRunLoopDoTimers + 276 (CFRunLoop.c:2512)
24  CoreFoundation                	0x00000001a31f353c __CFRunLoopRun + 1640 (CFRunLoop.c:0)
25  CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
26  GraphicsServices              	0x00000001ad362344 GSEventRunModal + 160 (GSEvent.c:2246)
27  UIKitCore                     	0x00000001a732e3e4 UIApplicationMain + 1932 (UIApplication.m:4823)
28  2P Chess Basic                	0x0000000100d98708 main + 64
29  libdyld.dylib                 	0x00000001a307a8f0 start + 4

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   Foundation                    	0x00000001a354401c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228 (NSRunLoop.m:374)
6   Foundation                    	0x00000001a3543efc -[NSRunLoop(NSRunLoop) runUntilDate:] + 88 (NSRunLoop.m:421)
7   UIKitCore                     	0x00000001a73d157c -[UIEventFetcher threadMain] + 152 (UIEventFetcher.m:733)
8   Foundation                    	0x00000001a3672e20 __NSThread__start__ + 848 (NSThread.m:724)
9   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
10  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   CFNetwork                     	0x00000001a64c05d0 -[__CoreSchedulingSetRunnable runForever] + 192 (CoreSchedulingSet.mm:1372)
6   Foundation                    	0x00000001a3672e20 __NSThread__start__ + 848 (NSThread.m:724)
7   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
8   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   Flutter                       	0x000000010160929c fml::MessageLoopDarwin::Run() + 88 (message_loop_darwin.mm:46)
6   Flutter                       	0x0000000101608c24 fml::MessageLoopImpl::DoRun() + 28 (message_loop_impl.cc:96)
7   Flutter                       	0x0000000101608c24 fml::MessageLoop::Run() + 32 (message_loop.cc:49)
8   Flutter                       	0x0000000101608c24 fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const + 144 (thread.cc:36)
9   Flutter                       	0x0000000101608c24 decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std:... + 144 (type_traits:4361)
10  Flutter                       	0x0000000101608c24 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::cha... + 144 (thread:342)
11  Flutter                       	0x0000000101608c24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char... + 196 (thread:352)
12  libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
13  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   Flutter                       	0x000000010160929c fml::MessageLoopDarwin::Run() + 88 (message_loop_darwin.mm:46)
6   Flutter                       	0x0000000101608c24 fml::MessageLoopImpl::DoRun() + 28 (message_loop_impl.cc:96)
7   Flutter                       	0x0000000101608c24 fml::MessageLoop::Run() + 32 (message_loop.cc:49)
8   Flutter                       	0x0000000101608c24 fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const + 144 (thread.cc:36)
9   Flutter                       	0x0000000101608c24 decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std:... + 144 (type_traits:4361)
10  Flutter                       	0x0000000101608c24 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::cha... + 144 (thread:342)
11  Flutter                       	0x0000000101608c24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char... + 196 (thread:352)
12  libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
13  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   Flutter                       	0x000000010160929c fml::MessageLoopDarwin::Run() + 88 (message_loop_darwin.mm:46)
6   Flutter                       	0x0000000101608c24 fml::MessageLoopImpl::DoRun() + 28 (message_loop_impl.cc:96)
7   Flutter                       	0x0000000101608c24 fml::MessageLoop::Run() + 32 (message_loop.cc:49)
8   Flutter                       	0x0000000101608c24 fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const + 144 (thread.cc:36)
9   Flutter                       	0x0000000101608c24 decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std:... + 144 (type_traits:4361)
10  Flutter                       	0x0000000101608c24 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::cha... + 144 (thread:342)
11  Flutter                       	0x0000000101608c24 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char... + 196 (thread:352)
12  libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
13  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib        	0x00000001a306fb58 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001a2f89ce4 _pthread_cond_wait$VARIANT$mp + 680 (pthread_cond.c:591)
2   libc++.1.dylib                	0x00000001a30c17ac std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24 (__threading_support:295)
3   Flutter                       	0x00000001016038f8 void std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) + 12 (__mutex_base:375)
4   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::WorkerMain() + 72 (concurrent_message_loop.cc:80)
5   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0::operator()() const + 176 (concurrent_message_loop.cc:26)
6   Flutter                       	0x00000001016038f8 decltype(std::__1::forward<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fp)()) std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fm... + 176 (type_traits:4361)
7   Flutter                       	0x00000001016038f8 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned lon... + 176 (thread:342)
8   Flutter                       	0x00000001016038f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLo... + 248 (thread:352)
9   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
10  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib        	0x00000001a306fb58 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001a2f89ce4 _pthread_cond_wait$VARIANT$mp + 680 (pthread_cond.c:591)
2   libc++.1.dylib                	0x00000001a30c17ac std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24 (__threading_support:295)
3   Flutter                       	0x00000001016038f8 void std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) + 12 (__mutex_base:375)
4   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::WorkerMain() + 72 (concurrent_message_loop.cc:80)
5   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0::operator()() const + 176 (concurrent_message_loop.cc:26)
6   Flutter                       	0x00000001016038f8 decltype(std::__1::forward<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fp)()) std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fm... + 176 (type_traits:4361)
7   Flutter                       	0x00000001016038f8 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned lon... + 176 (thread:342)
8   Flutter                       	0x00000001016038f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLo... + 248 (thread:352)
9   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
10  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 8 name:
Thread 8:
0   libsystem_kernel.dylib        	0x00000001a306fb58 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001a2f89ce4 _pthread_cond_wait$VARIANT$mp + 680 (pthread_cond.c:591)
2   libc++.1.dylib                	0x00000001a30c17ac std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24 (__threading_support:295)
3   Flutter                       	0x00000001016038f8 void std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) + 12 (__mutex_base:375)
4   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::WorkerMain() + 72 (concurrent_message_loop.cc:80)
5   Flutter                       	0x00000001016038f8 fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0::operator()() const + 176 (concurrent_message_loop.cc:26)
6   Flutter                       	0x00000001016038f8 decltype(std::__1::forward<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fp)()) std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>(fm... + 176 (type_traits:4361)
7   Flutter                       	0x00000001016038f8 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned lon... + 176 (thread:342)
8   Flutter                       	0x00000001016038f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLo... + 248 (thread:352)
9   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
10  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib        	0x00000001a3071868 kevent + 8
1   Flutter                       	0x0000000101987bac dart::bin::EventHandlerImplementation::EventHandlerEntry(unsigned long) + 340 (eventhandler_macos.cc:451)
2   Flutter                       	0x00000001019b5bb8 dart::bin::ThreadStart(void*) + 48 (thread_macos.cc:87)
3   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
4   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001a306fb58 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001a2f89ce4 _pthread_cond_wait$VARIANT$mp + 680 (pthread_cond.c:591)
2   libc++.1.dylib                	0x00000001a30c17ac std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24 (__threading_support:295)
3   JavaScriptCore                	0x00000001b218c904 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108 (condition_variable:203)
4   JavaScriptCore                	0x00000001b21905dc bmalloc::Scavenger::threadRunLoop() + 160 (condition_variable:212)
5   JavaScriptCore                	0x00000001b21902ec bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 12 (Scavenger.cpp:385)
6   JavaScriptCore                	0x00000001b2191530 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scaveng... + 40 (type_traits:4425)
7   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
8   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   AVFAudio                      	0x00000001affc2a2c GenericRunLoopThread::Entry(void*) + 156 (GenericRunLoopThread.h:91)
6   AVFAudio                      	0x00000001b00137a0 CAPThread::Entry(CAPThread*) + 204 (CAPThread.cpp:286)
7   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
8   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 12 name:
Thread 12:
0   libsystem_kernel.dylib        	0x00000001a304e198 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001a304d60c mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x00000001a31f8328 __CFRunLoopServiceMachPort + 148 (CFRunLoop.c:2575)
3   CoreFoundation                	0x00000001a31f335c __CFRunLoopRun + 1160 (CFRunLoop.c:2931)
4   CoreFoundation                	0x00000001a31f2ba8 CFRunLoopRunSpecific + 424 (CFRunLoop.c:3192)
5   AudioToolbox                  	0x00000001ae54b8fc GenericRunLoopThread::Entry(void*) + 156 (GenericRunLoopThread.h:91)
6   libAudioToolboxUtility.dylib  	0x00000001ae60c6a4 CAPThread::Entry(CAPThread*) + 88 (CAPThread.cpp:318)
7   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
8   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 13:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 17 name:
Thread 17:
0   Flutter                       	0x0000000101b1df08 dart::ForwardingBlock::Lookup(unsigned long) const + 12 (compactor.cc:48)
1   Flutter                       	0x0000000101b1df08 dart::ForwardingPage::Lookup(unsigned long) + 16 (compactor.cc:95)
2   Flutter                       	0x0000000101b1df08 dart::GCCompactor::ForwardPointer(dart::ObjectPtr*) + 136 (compactor.cc:625)
3   Flutter                       	0x0000000101b1df08 dart::GCCompactor::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*) + 148 (compactor.cc:668)
4   Flutter                       	0x0000000101b1df08 non-virtual thunk to dart::GCCompactor::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*) + 148 (compactor.cc:0)
5   Flutter                       	0x0000000101b1e4e4 dart::CompactorTask::SlideBlock(unsigned long, dart::ForwardingPage*) + 496 (compactor.cc:541)
6   Flutter                       	0x0000000101b1e4e4 dart::CompactorTask::SlidePage(dart::OldPage*) + 540 (compactor.cc:458)
7   Flutter                       	0x0000000101b1e4e4 dart::CompactorTask::RunEnteredIsolateGroup() + 1084 (compactor.cc:366)
8   Flutter                       	0x0000000101b1ee04 dart::GCCompactor::Compact(dart::OldPage*, dart::FreeList*, dart::Mutex*) + 988 (compactor.cc:256)
9   Flutter                       	0x0000000101b285ac dart::PageSpace::Compact(dart::Thread*) + 136 (pages.cc:1295)
10  Flutter                       	0x0000000101b285ac dart::PageSpace::CollectGarbageHelper(bool, bool, long long, long long) + 5352 (pages.cc:1188)
11  Flutter                       	0x0000000101b285ac dart::PageSpace::CollectGarbage(bool, bool) + 5760 (pages.cc:1072)
12  Flutter                       	0x0000000101b217d4 dart::Heap::CollectOldSpaceGarbage(dart::Thread*, dart::Heap::GCType, dart::Heap::GCReason) + 656 (heap.cc:513)
13  Flutter                       	0x0000000101a8afbc dart::Heap::CollectMostGarbage(dart::Heap::GCReason) + 36 (heap.cc:558)
14  Flutter                       	0x0000000101a8afbc dart::Heap::NotifyLowMemory() + 36 (heap.cc:424)
15  Flutter                       	0x0000000101a8afbc dart::IsolateMessageHandler::HandleLibMessage(dart::Array const&) + 1596 (isolate.cc:1131)
16  Flutter                       	0x0000000101a8a2a4 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >) + 3480 (isolate.cc:0)
17  Flutter                       	0x0000000101a967c0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) + 356 (message_handler.cc:233)
18  Flutter                       	0x0000000101a964ec dart::MessageHandler::TaskCallback() + 128 (message_handler.cc:443)
19  Flutter                       	0x0000000101a964ec dart::MessageHandlerTask::Run() + 176 (message_handler.cc:31)
20  Flutter                       	0x0000000101b1b31c dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) + 296 (thread_pool.cc:158)
21  Flutter                       	0x0000000101b1b31c dart::ThreadPool::Worker::Main(unsigned long) + 408 (thread_pool.cc:323)
22  Flutter                       	0x0000000101ad1384 dart::ThreadStart(void*) + 260 (os_thread_macos.cc:132)
23  libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
24  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 18:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 26:
0   libsystem_pthread.dylib       	0x00000001a2f94738 start_wqthread + 0

Thread 27 name:
Thread 27:
0   Flutter                       	0x0000000101b1e4cc std::__1::__atomic_base<unsigned int, true>::fetch_or(unsigned int, std::__1::memory_order) + 12 (atomic:1035)
1   Flutter                       	0x0000000101b1e4cc void dart::ObjectLayout::Tags::UpdateBool<dart::ObjectLayout::OldAndNotMarkedBit>(bool) + 12 (raw_object.h:241)
2   Flutter                       	0x0000000101b1e4cc dart::ObjectLayout::ClearMarkBit() + 12 (raw_object.h:303)
3   Flutter                       	0x0000000101b1e4cc dart::CompactorTask::SlideBlock(unsigned long, dart::ForwardingPage*) + 472 (compactor.cc:540)
4   Flutter                       	0x0000000101b1e4cc dart::CompactorTask::SlidePage(dart::OldPage*) + 516 (compactor.cc:458)
5   Flutter                       	0x0000000101b1e4cc dart::CompactorTask::RunEnteredIsolateGroup() + 1060 (compactor.cc:366)
6   Flutter                       	0x0000000101b1df84 dart::CompactorTask::Run() + 64 (compactor.cc:333)
7   Flutter                       	0x0000000101b1b31c dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) + 296 (thread_pool.cc:158)
8   Flutter                       	0x0000000101b1b31c dart::ThreadPool::Worker::Main(unsigned long) + 408 (thread_pool.cc:323)
9   Flutter                       	0x0000000101ad1384 dart::ThreadStart(void*) + 260 (os_thread_macos.cc:132)
10  libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
11  libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 28 name:
Thread 28:
0   libsystem_kernel.dylib        	0x00000001a306fb58 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001a2f89d18 _pthread_cond_wait$VARIANT$mp + 732 (pthread_cond.c:595)
2   Flutter                       	0x0000000101ad1a5c dart::Monitor::WaitMicros(long long) + 128 (os_thread_macos.cc:430)
3   Flutter                       	0x0000000101b1b420 dart::MonitorLocker::WaitMicros(long long) + 8 (lockers.h:181)
4   Flutter                       	0x0000000101b1b420 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) + 556 (thread_pool.cc:183)
5   Flutter                       	0x0000000101b1b420 dart::ThreadPool::Worker::Main(unsigned long) + 668 (thread_pool.cc:323)
6   Flutter                       	0x0000000101ad1384 dart::ThreadStart(void*) + 260 (os_thread_macos.cc:132)
7   libsystem_pthread.dylib       	0x00000001a2f90d98 _pthread_start + 156 (pthread.c:896)
8   libsystem_pthread.dylib       	0x00000001a2f9474c thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000282240f80   x1: 0x0000000000000002   x2: 0x00000001e4c9d7b0   x3: 0x000000000000000f
    x4: 0x0000000000000000   x5: 0x0000000000000007   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000002   x9: 0x0000000282240f80  x10: 0x0000000000000000  x11: 0x0000000200000002
   x12: 0x0000000000000034  x13: 0x00000001ee707328  x14: 0x0000000000000000  x15: 0x00000000000000a5
   x16: 0x00000001b0a2de80  x17: 0x00000001a315e798  x18: 0x0000000000000000  x19: 0x00000002839b9680
   x20: 0x0000000282240f80  x21: 0xe700000000000000  x22: 0x00000002837d2b20  x23: 0x00000002835493e0
   x24: 0xc032257390108cb2  x25: 0x00000001e4ca34f0  x26: 0x0000000000000002  x27: 0x000000000000000b
   x28: 0xc663571251d0edf3   fp: 0x000000016f069810   lr: 0x00000001012e16e0
    sp: 0x000000016f069760   pc: 0x00000001012e1b50 cpsr: 0x60000000
   esr: 0xf2000001  Address size fault
```
